
-- ==========================================
-- VIT CAMPUS MAP DATABASE SEED FILE
-- Auto-generated from JSON data
-- ==========================================

INSERT INTO map_nodes (id, floor, building, name, type, zone, pos_x, pos_y) VALUES 
('MB_ENT', 'G', 'MB', 'MB Main Entrance', 'Landmark', 'Exterior', 100, 190),
('MB_G_LOBBY', 'G', 'MB', 'Ground Floor Foyer', 'Corridor', 'Center', 100, 140),
('MB_G01', 'G', 'MB', 'Channa Reddy Auditorium', 'Auditorium', 'West Wing', 50, 140),
('MB_G02', 'G', 'MB', 'Admissions Office', 'Office', 'East Wing', 150, 140),
('MB_G03', 'G', 'MB', 'Finance Office & Cash Counter', 'Office', 'North Wing', 100, 90),
('MB_G04', 'G', 'MB', 'Indian Bank & Post Office', 'Landmark', 'East Wing', 180, 140),
('MB_1_LOBBY', '1', 'MB', 'First Floor Elevators', 'Elevator', 'Center', 100, 140),
('MB_101', '1', 'MB', 'Vice Chancellor''s Office', 'Office', 'West Wing', 50, 140),
('MB_102', '1', 'MB', 'Pro-Vice Chancellor''s Office', 'Office', 'West Wing', 30, 140),
('MB_103', '1', 'MB', 'Registrar''s Office', 'Office', 'East Wing', 150, 140),
('MB_104', '1', 'MB', 'Main Board Room', 'Office', 'North Wing', 100, 90),
('MB_2_LOBBY', '2', 'MB', 'Second Floor Elevators', 'Elevator', 'Center', 100, 140),
('MB_201', '2', 'MB', 'Rajaji Hall', 'Auditorium', 'West Wing', 50, 140),
('MB_202', '2', 'MB', 'SAS (School of Advanced Sciences) Dean Office', 'Office', 'East Wing', 150, 140),
('MB_203', '2', 'MB', 'Engineering Chemistry Lab 1', 'Lab', 'North Wing', 100, 90),
('MB_204', '2', 'MB', 'Engineering Chemistry Lab 2', 'Lab', 'North Wing', 100, 60),
('MB_3_LOBBY', '3', 'MB', 'Third Floor Elevators', 'Elevator', 'Center', 100, 140),
('MB_301', '3', 'MB', 'Srinivasa Ramanujan Hall', 'Auditorium', 'West Wing', 50, 140),
('MB_302', '3', 'MB', 'Engineering Physics Lab', 'Lab', 'East Wing', 150, 140),
('MB_303', '3', 'MB', 'English Language Lab', 'Lab', 'North Wing', 100, 90),
('MB_304', '3', 'MB', 'Mathematics Faculty Cabins', 'Office', 'South Wing', 100, 190),
('PRP_node_entrance_G', 'G', 'PRP', 'Main Entrance', 'Waypoint', 'Exterior', 50, 95),
('PRP_node_lobby_G', 'G', 'PRP', 'Ground Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_G', 'G', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_G', 'G', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_G', 'G', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_G', 'G', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_G03', 'G', 'PRP', 'Classroom', 'Academic', 'Right Wing', 70, 45),
('PRP_G06', 'G', 'PRP', 'Classroom', 'Academic', 'Right Wing', 75, 35),
('PRP_G08', 'G', 'PRP', 'Classroom', 'Academic', 'Right Wing', 80, 25),
('PRP_G10', 'G', 'PRP', 'Classroom', 'Academic', 'Right Wing', 85, 15),
('PRP_G13', 'G', 'PRP', 'Male Staff Restroom', 'Restroom', 'Back Wing', 65, 20),
('PRP_G14', 'G', 'PRP', 'SCOPE School Office', 'Admin', 'Right Wing', 85, 50),
('PRP_G19', 'G', 'PRP', 'Faculty Cabins', 'Faculty', 'Right Wing', 90, 60),
('PRP_G04', 'G', 'PRP', 'M.Sc. Chemistry Lab', 'Lab', 'Left Wing', 20, 45),
('PRP_G07', 'G', 'PRP', 'B.Tech Chemistry Lab', 'Lab', 'Left Wing', 15, 35),
('PRP_G17', 'G', 'PRP', 'B.Tech Physics Lab', 'Lab', 'Left Wing', 10, 25),
('PRP_G18', 'G', 'PRP', 'M.Sc. Physics Lab', 'Lab', 'Left Wing', 5, 15),
('PRP_G01', 'G', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_G02', 'G', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_G05', 'G', 'PRP', 'Electrical Room', 'Service', 'Back Wing', 35, 20),
('PRP_G09', 'G', 'PRP', 'Food Court', 'Amenity', 'Back Wing', 50, 5),
('PRP_G15', 'G', 'PRP', 'Clean Env Lab 1', 'Lab', 'Back Wing', 30, 15),
('PRP_G16', 'G', 'PRP', 'Clean Env Lab 2', 'Lab', 'Back Wing', 70, 15),
('PRP_node_lobby_1', '1', 'PRP', '1st Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_1', '1', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_1', '1', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_1', '1', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_1', '1', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_101', '1', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 70, 45),
('PRP_102', '1', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 75, 35),
('PRP_103', '1', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 80, 25),
('PRP_104', '1', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 85, 15),
('PRP_105', '1', 'PRP', 'Faculty Cabins', 'Faculty', 'Right Wing', 90, 60),
('PRP_106', '1', 'PRP', 'Gallery Hall A', 'Academic', 'Left Wing', 20, 45),
('PRP_107', '1', 'PRP', 'Gallery Hall B', 'Academic', 'Left Wing', 15, 35),
('PRP_108', '1', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 10, 25),
('PRP_109', '1', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 5, 15),
('PRP_110', '1', 'PRP', 'Meeting Room', 'Admin', 'Left Wing', 20, 55),
('PRP_111', '1', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_112', '1', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_114', '1', 'PRP', 'Dean''s Office', 'Admin', 'Back Wing', 50, 10),
('PRP_115', '1', 'PRP', 'Seminar Room', 'Academic', 'Back Wing', 65, 15),
('PRP_node_lobby_2', '2', 'PRP', '2nd Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_2', '2', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_2', '2', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_2', '2', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_2', '2', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_201', '2', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 70, 45),
('PRP_202', '2', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 75, 35),
('PRP_203', '2', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 80, 25),
('PRP_204', '2', 'PRP', 'Smart Classroom', 'Academic', 'Right Wing', 85, 15),
('PRP_205', '2', 'PRP', 'Faculty Cabins', 'Faculty', 'Right Wing', 90, 60),
('PRP_206', '2', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 20, 45),
('PRP_207', '2', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 15, 35),
('PRP_208', '2', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 10, 25),
('PRP_209', '2', 'PRP', 'Smart Classroom', 'Academic', 'Left Wing', 5, 15),
('PRP_210', '2', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_211', '2', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_212', '2', 'PRP', 'Project Room A', 'Academic', 'Back Wing', 35, 10),
('PRP_213', '2', 'PRP', 'Project Room B', 'Academic', 'Back Wing', 65, 10),
('PRP_node_lobby_3', '3', 'PRP', '3rd Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_3', '3', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_3', '3', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_3', '3', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_3', '3', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_301', '3', 'PRP', 'AI & Machine Learning Lab', 'Lab', 'Right Wing', 75, 35),
('PRP_302', '3', 'PRP', 'AI & Machine Learning Lab 2', 'Lab', 'Right Wing', 80, 25),
('PRP_303', '3', 'PRP', 'High Performance Computing Lab', 'Lab', 'Right Wing', 85, 15),
('PRP_304', '3', 'PRP', 'Faculty Cabins - SCOPE', 'Faculty', 'Right Wing', 90, 60),
('PRP_305', '3', 'PRP', 'IoT Systems Lab', 'Lab', 'Left Wing', 20, 45),
('PRP_306', '3', 'PRP', 'IoT Systems Lab 2', 'Lab', 'Left Wing', 15, 35),
('PRP_307', '3', 'PRP', 'Cloud Computing Lab', 'Lab', 'Left Wing', 10, 25),
('PRP_308', '3', 'PRP', 'Server Room', 'Service', 'Left Wing', 5, 15),
('PRP_310', '3', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_311', '3', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_312', '3', 'PRP', 'Computer Networks Lab', 'Lab', 'Back Wing', 35, 10),
('PRP_313', '3', 'PRP', 'Computer Networks Lab 2', 'Lab', 'Back Wing', 65, 10),
('PRP_node_lobby_4', '4', 'PRP', '4th Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_4', '4', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_4', '4', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_4', '4', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_4', '4', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_401', '4', 'PRP', 'Data Science Lab 1', 'Lab', 'Right Wing', 75, 35),
('PRP_402', '4', 'PRP', 'Data Science Lab 2', 'Lab', 'Right Wing', 80, 25),
('PRP_403', '4', 'PRP', 'Big Data Analytics Lab', 'Lab', 'Right Wing', 85, 15),
('PRP_404', '4', 'PRP', 'Faculty Cabins', 'Faculty', 'Right Wing', 90, 60),
('PRP_405', '4', 'PRP', 'Virtual Reality Simulation Lab', 'Lab', 'Left Wing', 20, 45),
('PRP_406', '4', 'PRP', 'Computer Graphics Lab', 'Lab', 'Left Wing', 15, 35),
('PRP_407', '4', 'PRP', 'Software Engineering Lab', 'Lab', 'Left Wing', 10, 25),
('PRP_408', '4', 'PRP', 'Cybersecurity Lab', 'Lab', 'Left Wing', 5, 15),
('PRP_410', '4', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_411', '4', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_412', '4', 'PRP', 'Open Source Tech Lab', 'Lab', 'Back Wing', 35, 10),
('PRP_413', '4', 'PRP', 'General Computing Lab', 'Lab', 'Back Wing', 65, 10),
('PRP_node_lobby_5', '5', 'PRP', '5th Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_5', '5', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_5', '5', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_5', '5', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_5', '5', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_501', '5', 'PRP', 'App Development Lab', 'Lab', 'Right Wing', 75, 35),
('PRP_502', '5', 'PRP', 'Web Technology Lab', 'Lab', 'Right Wing', 80, 25),
('PRP_503', '5', 'PRP', 'Blockchain Research Center', 'Lab', 'Right Wing', 85, 15),
('PRP_504', '5', 'PRP', 'Faculty Cabins', 'Faculty', 'Right Wing', 90, 60),
('PRP_505', '5', 'PRP', 'Database Systems Lab', 'Lab', 'Left Wing', 20, 45),
('PRP_506', '5', 'PRP', 'Operating Systems Lab', 'Lab', 'Left Wing', 15, 35),
('PRP_507', '5', 'PRP', 'General Computing Lab', 'Lab', 'Left Wing', 10, 25),
('PRP_508', '5', 'PRP', 'General Computing Lab', 'Lab', 'Left Wing', 5, 15),
('PRP_510', '5', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_511', '5', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_512', '5', 'PRP', 'Meeting Room 5A', 'Admin', 'Back Wing', 35, 10),
('PRP_513', '5', 'PRP', 'Meeting Room 5B', 'Admin', 'Back Wing', 65, 10),
('PRP_node_lobby_6', '6', 'PRP', '6th Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_6', '6', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_6', '6', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_6', '6', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_6', '6', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_601', '6', 'PRP', 'Industry Tech Park - Center A', 'Research', 'Right Wing', 75, 35),
('PRP_602', '6', 'PRP', 'Industry Tech Park - Center B', 'Research', 'Right Wing', 80, 25),
('PRP_603', '6', 'PRP', 'Conference Center', 'Admin', 'Right Wing', 85, 15),
('PRP_605', '6', 'PRP', 'Research Scholar Workspace', 'Research', 'Left Wing', 20, 45),
('PRP_606', '6', 'PRP', 'Research Scholar Workspace', 'Research', 'Left Wing', 15, 35),
('PRP_607', '6', 'PRP', 'Advanced Electronics Lab', 'Lab', 'Left Wing', 10, 25),
('PRP_610', '6', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_611', '6', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_612', '6', 'PRP', 'Executive Lounge', 'Amenity', 'Back Wing', 35, 10),
('PRP_613', '6', 'PRP', 'Server Architecture Hub', 'Service', 'Back Wing', 65, 10),
('PRP_node_lobby_7', '7', 'PRP', '7th Floor Lobby', 'Waypoint', 'Core', 50, 60),
('PRP_node_lift_7', '7', 'PRP', 'Main Elevators', 'Transport', 'Core', 50, 50),
('PRP_node_corr_right_7', '7', 'PRP', 'Right Corridor', 'Corridor', 'Right Wing', 75, 50),
('PRP_node_corr_left_7', '7', 'PRP', 'Left Corridor', 'Corridor', 'Left Wing', 25, 50),
('PRP_node_corr_back_7', '7', 'PRP', 'Back Corridor', 'Corridor', 'Back Wing', 50, 20),
('PRP_701', '7', 'PRP', 'Advanced Materials Research', 'Research', 'Right Wing', 75, 35),
('PRP_702', '7', 'PRP', 'Nanotechnology Lab', 'Research', 'Right Wing', 80, 25),
('PRP_703', '7', 'PRP', 'Faculty Cabins - SAS', 'Faculty', 'Right Wing', 85, 15),
('PRP_705', '7', 'PRP', 'Advanced Chemistry Wet Lab', 'Lab', 'Left Wing', 20, 45),
('PRP_706', '7', 'PRP', 'Advanced Biology Wet Lab', 'Lab', 'Left Wing', 15, 35),
('PRP_707', '7', 'PRP', 'Spectroscopy Center', 'Lab', 'Left Wing', 10, 25),
('PRP_710', '7', 'PRP', 'Ladies Restroom', 'Restroom', 'Back Wing', 40, 25),
('PRP_711', '7', 'PRP', 'Gents Restroom', 'Restroom', 'Back Wing', 60, 25),
('PRP_712', '7', 'PRP', 'Roof Access / Maintenance', 'Service', 'Back Wing', 35, 10),
('sjt_entrance_G', 'G', 'SJT', 'SJT Main Entrance', 'Waypoint', 'Exterior', 50, 95),
('sjt_atrium_G', 'G', 'SJT', 'Ground Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_G', 'G', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_G', 'G', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_G', 'G', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_G', 'G', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_G', 'G', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_G13', 'G', 'SJT', 'Arasan Canteen', 'Amenity', 'North Wing', 50, 10),
('SJT_G11', 'G', 'SJT', 'Dining Hall 1', 'Amenity', 'North Wing', 40, 15),
('SJT_G12', 'G', 'SJT', 'Dining Hall 2', 'Amenity', 'North Wing', 60, 15),
('SJT_PAT_Office', 'G', 'SJT', 'Placement & Training (PAT) Office', 'Admin', 'South Wing', 50, 85),
('SJT_G01', 'G', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_G14', 'G', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_G17', 'G', 'SJT', 'Software Development & Management Lab', 'Lab', 'East Wing', 85, 40),
('SJT_G18', 'G', 'SJT', 'Embedded Systems & IoT Lab', 'Lab', 'East Wing', 85, 60),
('SJT_G16', 'G', 'SJT', 'Classroom', 'Academic', 'East Wing', 75, 60),
('sjt_restroom_M_G', 'G', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_G', 'G', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_1', '1', 'SJT', '1st Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_1', '1', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_1', '1', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_1', '1', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_1', '1', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_1', '1', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_121A', '1', 'SJT', 'Innovation Lab (SITE)', 'Lab', 'North Wing', 40, 15),
('SJT_122', '1', 'SJT', 'Software Testing & Verification Lab', 'Lab', 'North Wing', 60, 15),
('SJT_124', '1', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_125', '1', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_126', '1', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_127', '1', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_130', '1', 'SJT', 'NAAC Room', 'Admin', 'East Wing', 85, 40),
('SJT_131', '1', 'SJT', 'SITE Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('sjt_restroom_M_1', '1', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_1', '1', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('SJT_123', '1', 'SJT', 'Staff Restrooms', 'Restroom', 'West Wing', 10, 50),
('sjt_atrium_2', '2', 'SJT', '2nd Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_2', '2', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_2', '2', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_2', '2', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_2', '2', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_2', '2', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_216', '2', 'SJT', 'Web Development Lab', 'Lab', 'North Wing', 40, 15),
('SJT_217', '2', 'SJT', 'Information & Network Security Lab', 'Lab', 'North Wing', 60, 15),
('SJT_218', '2', 'SJT', 'Artificial Intelligence Lab', 'Lab', 'North Wing', 40, 5),
('SJT_219', '2', 'SJT', 'Computer Vision Lab', 'Lab', 'North Wing', 60, 5),
('SJT_207A', '2', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_208', '2', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_211', '2', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_215', '2', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_210', '2', 'SJT', 'Staff Rooms (Mixed)', 'Faculty', 'East Wing', 85, 40),
('SJT_213', '2', 'SJT', 'Staff Rooms (Mixed)', 'Faculty', 'East Wing', 85, 60),
('SJT_217A', '2', 'SJT', 'Research Cabin', 'Faculty', 'East Wing', 90, 50),
('SJT_209', '2', 'SJT', 'Boys Toilet', 'Restroom', 'West Wing', 15, 40),
('SJT_214', '2', 'SJT', 'Girls Toilet', 'Restroom', 'West Wing', 15, 60),
('SJT_220', '2', 'SJT', 'Staff Toilet', 'Restroom', 'West Wing', 10, 50),
('sjt_atrium_3', '3', 'SJT', '3rd Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_3', '3', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_3', '3', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_3', '3', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_3', '3', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_3', '3', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_301', '3', 'SJT', 'SCOPE Lab', 'Lab', 'North Wing', 40, 15),
('SJT_302', '3', 'SJT', 'SCOPE Lab', 'Lab', 'North Wing', 60, 15),
('SJT_303', '3', 'SJT', 'SCOPE Lab', 'Lab', 'North Wing', 40, 5),
('SJT_304', '3', 'SJT', 'SCOPE Lab', 'Lab', 'North Wing', 60, 5),
('SJT_305', '3', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_306', '3', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_307', '3', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_308', '3', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_309', '3', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_310', '3', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_311', '3', 'SJT', 'Meeting Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_3', '3', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_3', '3', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_4', '4', 'SJT', '4th Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_4', '4', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_4', '4', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_4', '4', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_4', '4', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_4', '4', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_401', '4', 'SJT', 'Computer Lab A', 'Lab', 'North Wing', 40, 15),
('SJT_402', '4', 'SJT', 'Computer Lab B', 'Lab', 'North Wing', 60, 15),
('SJT_403', '4', 'SJT', 'Computer Lab C', 'Lab', 'North Wing', 40, 5),
('SJT_404', '4', 'SJT', 'Computer Lab D', 'Lab', 'North Wing', 60, 5),
('SJT_405', '4', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_406', '4', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_407', '4', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_408', '4', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_409', '4', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_410', '4', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_411', '4', 'SJT', 'Meeting Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_4', '4', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_4', '4', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_5', '5', 'SJT', '5th Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_5', '5', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_5', '5', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_5', '5', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_5', '5', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_5', '5', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_501', '5', 'SJT', 'Computer Lab', 'Lab', 'North Wing', 40, 15),
('SJT_502', '5', 'SJT', 'Computer Lab', 'Lab', 'North Wing', 60, 15),
('SJT_503', '5', 'SJT', 'Computer Lab', 'Lab', 'North Wing', 40, 5),
('SJT_504', '5', 'SJT', 'Computer Lab', 'Lab', 'North Wing', 60, 5),
('SJT_505', '5', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_506', '5', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_507', '5', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_508', '5', 'SJT', 'Smart Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_509', '5', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_510', '5', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_511', '5', 'SJT', 'Discussion Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_5', '5', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_5', '5', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_6', '6', 'SJT', '6th Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_6', '6', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_6', '6', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_6', '6', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_6', '6', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_6', '6', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_601', '6', 'SJT', 'Specialized Lab', 'Lab', 'North Wing', 40, 15),
('SJT_602', '6', 'SJT', 'Specialized Lab', 'Lab', 'North Wing', 60, 15),
('SJT_603', '6', 'SJT', 'Project Workspace', 'Academic', 'North Wing', 40, 5),
('SJT_604', '6', 'SJT', 'Project Workspace', 'Academic', 'North Wing', 60, 5),
('SJT_605', '6', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_606', '6', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_607', '6', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_608', '6', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_609', '6', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_610', '6', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_611', '6', 'SJT', 'Meeting Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_6', '6', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_6', '6', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_7', '7', 'SJT', '7th Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_7', '7', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_7', '7', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_7', '7', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_7', '7', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_7', '7', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_701', '7', 'SJT', 'Advanced Research Lab', 'Lab', 'North Wing', 40, 15),
('SJT_702', '7', 'SJT', 'Advanced Research Lab', 'Lab', 'North Wing', 60, 15),
('SJT_703', '7', 'SJT', 'Scholar Workspace', 'Academic', 'North Wing', 40, 5),
('SJT_704', '7', 'SJT', 'Scholar Workspace', 'Academic', 'North Wing', 60, 5),
('SJT_705', '7', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_706', '7', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_707', '7', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_708', '7', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_709', '7', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_710', '7', 'SJT', 'Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_711', '7', 'SJT', 'Meeting Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_7', '7', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_7', '7', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('sjt_atrium_8', '8', 'SJT', '8th Floor Atrium', 'Waypoint', 'Core', 50, 50),
('sjt_lift_8', '8', 'SJT', 'Main Elevators', 'Transport', 'Core', 50, 40),
('sjt_corr_N_8', '8', 'SJT', 'North Corridor', 'Corridor', 'North Wing', 50, 20),
('sjt_corr_S_8', '8', 'SJT', 'South Corridor', 'Corridor', 'South Wing', 50, 80),
('sjt_corr_E_8', '8', 'SJT', 'East Corridor', 'Corridor', 'East Wing', 80, 50),
('sjt_corr_W_8', '8', 'SJT', 'West Corridor', 'Corridor', 'West Wing', 20, 50),
('SJT_801', '8', 'SJT', 'Center of Excellence Lab', 'Lab', 'North Wing', 40, 15),
('SJT_802', '8', 'SJT', 'Center of Excellence Lab', 'Lab', 'North Wing', 60, 15),
('SJT_803', '8', 'SJT', 'Research Workspace', 'Academic', 'North Wing', 40, 5),
('SJT_804', '8', 'SJT', 'Research Workspace', 'Academic', 'North Wing', 60, 5),
('SJT_805', '8', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 75),
('SJT_806', '8', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 75),
('SJT_807', '8', 'SJT', 'Classroom', 'Academic', 'South Wing', 40, 85),
('SJT_808', '8', 'SJT', 'Classroom', 'Academic', 'South Wing', 60, 85),
('SJT_809', '8', 'SJT', 'Senior Faculty Cabins', 'Faculty', 'East Wing', 85, 40),
('SJT_810', '8', 'SJT', 'Senior Faculty Cabins', 'Faculty', 'East Wing', 85, 60),
('SJT_811', '8', 'SJT', 'Board Room', 'Admin', 'East Wing', 90, 50),
('sjt_restroom_M_8', '8', 'SJT', 'Gents Restroom', 'Restroom', 'West Wing', 15, 45),
('sjt_restroom_F_8', '8', 'SJT', 'Ladies Restroom', 'Restroom', 'West Wing', 15, 55),
('SJT_411', '4', 'SJT', 'Homi J. Bhabha Gallery', 'Auditorium', 'Central Hub', 120, 100),
('SJT_511', '5', 'SJT', 'P.V. Narasimha Rao Gallery', 'Auditorium', 'Central Hub', 120, 100),
('SJT_611', '6', 'SJT', 'Sarojini Naidu Gallery', 'Auditorium', 'Central Hub', 120, 100),
('SJT_811', '8', 'SJT', 'Bhagat Singh Gallery', 'Auditorium', 'Central Hub', 120, 100),
('SJT_G_FOOD', 'G', 'SJT', 'SJT Food Court (Dominos/Lounge)', 'Landmark', 'East Wing', 160, 140),
('SJT_3_PAT', '3', 'SJT', 'PAT (Placement & Training) Centre', 'Office', 'North Wing', 120, 60),
('SJT_3_GD', '3', 'SJT', 'PAT Group Discussion Cabins', 'Academic', 'North Wing', 140, 60),
('SJT_G_LOBBY', 'G', 'SJT', 'Ground Floor Elevators', 'Elevator', 'Center', 100, 140),
('SJT_3_LOBBY', '3', 'SJT', 'Third Floor Elevators', 'Elevator', 'Center', 100, 140),
('SJT_4_LOBBY', '4', 'SJT', 'Fourth Floor Elevators', 'Elevator', 'Center', 100, 140),
('SJT_5_LOBBY', '5', 'SJT', 'Fifth Floor Elevators', 'Elevator', 'Center', 100, 140),
('SJT_6_LOBBY', '6', 'SJT', 'Sixth Floor Elevators', 'Elevator', 'Center', 100, 140),
('SJT_8_LOBBY', '8', 'SJT', 'Eighth Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_ENT', 'G', 'TT', 'TT Main Entrance', 'Landmark', 'South Wing', 100, 190),
('TT_G_LOBBY', 'G', 'TT', 'Ground Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_G01', 'G', 'TT', 'Dr. Ambedkar Auditorium', 'Auditorium', 'West Wing', 50, 140),
('TT_G02', 'G', 'TT', 'Kamaraj Auditorium', 'Auditorium', 'East Wing', 150, 140),
('TT_G03', 'G', 'TT', 'TBI Incubation Centre', 'Lab', 'North Wing', 100, 90),
('TT_1_LOBBY', '1', 'TT', 'First Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_101', '1', 'TT', 'Centre for Nanotechnology', 'Lab', 'West Wing', 50, 140),
('TT_102', '1', 'TT', 'Advanced Materials Lab', 'Lab', 'East Wing', 150, 140),
('TT_103', '1', 'TT', 'Biomedical Engineering Lab', 'Lab', 'North Wing', 100, 90),
('TT_104', '1', 'TT', 'Smart Classroom 1', 'Classroom', 'South Wing', 100, 190),
('TT_2_LOBBY', '2', 'TT', 'Second Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_201', '2', 'TT', 'VOC Gallery', 'Auditorium', 'West Wing', 50, 140),
('TT_202', '2', 'TT', 'Fluid Mechanics Lab', 'Lab', 'East Wing', 150, 140),
('TT_203', '2', 'TT', 'Thermal Engineering Lab', 'Lab', 'North Wing', 100, 90),
('TT_204', '2', 'TT', 'Mechatronics Lab', 'Lab', 'South Wing', 100, 190),
('TT_3_LOBBY', '3', 'TT', 'Third Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_301', '3', 'TT', 'Software Engineering Lab', 'Lab', 'West Wing', 50, 140),
('TT_302', '3', 'TT', 'Database Systems Lab', 'Lab', 'East Wing', 150, 140),
('TT_303', '3', 'TT', 'Network & Security Lab', 'Lab', 'North Wing', 100, 90),
('TT_304', '3', 'TT', 'AI & Machine Learning Lab', 'Lab', 'South Wing', 100, 190),
('TT_4_LOBBY', '4', 'TT', 'Fourth Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_401', '4', 'TT', 'Electronics Lab', 'Lab', 'West Wing', 50, 140),
('TT_402', '4', 'TT', 'Microprocessor Lab', 'Lab', 'East Wing', 150, 140),
('TT_403', '4', 'TT', 'VLSI Design Lab', 'Lab', 'North Wing', 100, 90),
('TT_404', '4', 'TT', 'Embedded Systems Lab', 'Lab', 'South Wing', 100, 190),
('TT_5_LOBBY', '5', 'TT', 'Fifth Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_501', '5', 'TT', 'Cyber Security Lab', 'Lab', 'West Wing', 50, 140),
('TT_502', '5', 'TT', 'Cloud Computing Lab', 'Lab', 'East Wing', 150, 140),
('TT_503', '5', 'TT', 'Data Science Lab', 'Lab', 'North Wing', 100, 90),
('TT_504', '5', 'TT', 'AR/VR Development Lab', 'Lab', 'South Wing', 100, 190),
('TT_6_LOBBY', '6', 'TT', 'Sixth Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_601', '6', 'TT', 'Robotics Lab', 'Lab', 'West Wing', 50, 140),
('TT_602', '6', 'TT', 'Automotive Engineering Lab', 'Lab', 'East Wing', 150, 140),
('TT_603', '6', 'TT', 'Advanced Manufacturing Lab', 'Lab', 'North Wing', 100, 90),
('TT_604', '6', 'TT', 'CAD/CAM Lab', 'Lab', 'South Wing', 100, 190),
('TT_7_LOBBY', '7', 'TT', 'Seventh Floor Elevators', 'Elevator', 'Center', 100, 140),
('TT_701', '7', 'TT', 'Dean''s Office', 'Office', 'West Wing', 50, 140),
('TT_702', '7', 'TT', 'Psychometric Lab', 'Lab', 'East Wing', 150, 140),
('TT_703', '7', 'TT', 'Executive Board Room', 'Office', 'North Wing', 100, 90),
('TT_704', '7', 'TT', 'Faculty Cabins (SMEC)', 'Office', 'South Wing', 100, 190),
('TT_G_FOOD', 'G', 'TT', 'TT Food Court / Woodys', 'Landmark', 'South Wing', 100, 220),
('TT_1_LIBRARY', '1', 'TT', 'SMEC Department Library', 'Academic', 'West Wing', 30, 140)
ON CONFLICT (id) DO UPDATE SET 
      floor = EXCLUDED.floor, 
      building = EXCLUDED.building, 
      name = EXCLUDED.name, 
      type = EXCLUDED.type, 
      zone = EXCLUDED.zone, 
      pos_x = EXCLUDED.pos_x, 
      pos_y = EXCLUDED.pos_y;


INSERT INTO map_edges (source_node, target_node) VALUES 
('MB_ENT', 'MB_G_LOBBY'),
('MB_G_LOBBY', 'MB_G01'),
('MB_G_LOBBY', 'MB_G02'),
('MB_G_LOBBY', 'MB_G03'),
('MB_G02', 'MB_G04'),
('MB_1_LOBBY', 'MB_101'),
('MB_101', 'MB_102'),
('MB_1_LOBBY', 'MB_103'),
('MB_1_LOBBY', 'MB_104'),
('MB_2_LOBBY', 'MB_201'),
('MB_2_LOBBY', 'MB_202'),
('MB_2_LOBBY', 'MB_203'),
('MB_203', 'MB_204'),
('MB_3_LOBBY', 'MB_301'),
('MB_3_LOBBY', 'MB_302'),
('MB_3_LOBBY', 'MB_303'),
('MB_3_LOBBY', 'MB_304'),
('MB_G_LOBBY', 'MB_1_LOBBY'),
('MB_1_LOBBY', 'MB_2_LOBBY'),
('MB_2_LOBBY', 'MB_3_LOBBY'),
('PRP_node_entrance_G', 'PRP_node_lobby_G'),
('PRP_node_lobby_G', 'PRP_node_entrance_G'),
('PRP_node_lobby_G', 'PRP_node_lift_G'),
('PRP_node_lobby_G', 'PRP_node_corr_right_G'),
('PRP_node_lobby_G', 'PRP_node_corr_left_G'),
('PRP_node_lobby_G', 'PRP_node_corr_back_G'),
('PRP_node_lift_G', 'PRP_node_lobby_G'),
('PRP_node_lift_G', 'PRP_node_lift_1'),
('PRP_node_corr_right_G', 'PRP_node_lobby_G'),
('PRP_node_corr_right_G', 'PRP_G03'),
('PRP_node_corr_right_G', 'PRP_G06'),
('PRP_node_corr_right_G', 'PRP_G08'),
('PRP_node_corr_right_G', 'PRP_G10'),
('PRP_node_corr_right_G', 'PRP_G14'),
('PRP_node_corr_right_G', 'PRP_G19'),
('PRP_node_corr_left_G', 'PRP_node_lobby_G'),
('PRP_node_corr_left_G', 'PRP_G04'),
('PRP_node_corr_left_G', 'PRP_G07'),
('PRP_node_corr_left_G', 'PRP_G17'),
('PRP_node_corr_left_G', 'PRP_G18'),
('PRP_node_corr_back_G', 'PRP_node_lobby_G'),
('PRP_node_corr_back_G', 'PRP_G01'),
('PRP_node_corr_back_G', 'PRP_G02'),
('PRP_node_corr_back_G', 'PRP_G05'),
('PRP_node_corr_back_G', 'PRP_G09'),
('PRP_node_corr_back_G', 'PRP_G13'),
('PRP_node_corr_back_G', 'PRP_G15'),
('PRP_node_corr_back_G', 'PRP_G16'),
('PRP_G03', 'PRP_node_corr_right_G'),
('PRP_G06', 'PRP_node_corr_right_G'),
('PRP_G08', 'PRP_node_corr_right_G'),
('PRP_G10', 'PRP_node_corr_right_G'),
('PRP_G13', 'PRP_node_corr_back_G'),
('PRP_G14', 'PRP_node_corr_right_G'),
('PRP_G19', 'PRP_node_corr_right_G'),
('PRP_G04', 'PRP_node_corr_left_G'),
('PRP_G07', 'PRP_node_corr_left_G'),
('PRP_G17', 'PRP_node_corr_left_G'),
('PRP_G18', 'PRP_node_corr_left_G'),
('PRP_G01', 'PRP_node_corr_back_G'),
('PRP_G02', 'PRP_node_corr_back_G'),
('PRP_G05', 'PRP_node_corr_back_G'),
('PRP_G09', 'PRP_node_corr_back_G'),
('PRP_G15', 'PRP_node_corr_back_G'),
('PRP_G16', 'PRP_node_corr_back_G'),
('PRP_node_lobby_1', 'PRP_node_lift_1'),
('PRP_node_lobby_1', 'PRP_node_corr_right_1'),
('PRP_node_lobby_1', 'PRP_node_corr_left_1'),
('PRP_node_lobby_1', 'PRP_node_corr_back_1'),
('PRP_node_lift_1', 'PRP_node_lobby_1'),
('PRP_node_lift_1', 'PRP_node_lift_G'),
('PRP_node_lift_1', 'PRP_node_lift_2'),
('PRP_node_corr_right_1', 'PRP_node_lobby_1'),
('PRP_node_corr_right_1', 'PRP_101'),
('PRP_node_corr_right_1', 'PRP_102'),
('PRP_node_corr_right_1', 'PRP_103'),
('PRP_node_corr_right_1', 'PRP_104'),
('PRP_node_corr_right_1', 'PRP_105'),
('PRP_node_corr_left_1', 'PRP_node_lobby_1'),
('PRP_node_corr_left_1', 'PRP_106'),
('PRP_node_corr_left_1', 'PRP_107'),
('PRP_node_corr_left_1', 'PRP_108'),
('PRP_node_corr_left_1', 'PRP_109'),
('PRP_node_corr_left_1', 'PRP_110'),
('PRP_node_corr_back_1', 'PRP_node_lobby_1'),
('PRP_node_corr_back_1', 'PRP_111'),
('PRP_node_corr_back_1', 'PRP_112'),
('PRP_node_corr_back_1', 'PRP_114'),
('PRP_node_corr_back_1', 'PRP_115'),
('PRP_101', 'PRP_node_corr_right_1'),
('PRP_102', 'PRP_node_corr_right_1'),
('PRP_103', 'PRP_node_corr_right_1'),
('PRP_104', 'PRP_node_corr_right_1'),
('PRP_105', 'PRP_node_corr_right_1'),
('PRP_106', 'PRP_node_corr_left_1'),
('PRP_107', 'PRP_node_corr_left_1'),
('PRP_108', 'PRP_node_corr_left_1'),
('PRP_109', 'PRP_node_corr_left_1'),
('PRP_110', 'PRP_node_corr_left_1'),
('PRP_111', 'PRP_node_corr_back_1'),
('PRP_112', 'PRP_node_corr_back_1'),
('PRP_114', 'PRP_node_corr_back_1'),
('PRP_115', 'PRP_node_corr_back_1'),
('PRP_node_lobby_2', 'PRP_node_lift_2'),
('PRP_node_lobby_2', 'PRP_node_corr_right_2'),
('PRP_node_lobby_2', 'PRP_node_corr_left_2'),
('PRP_node_lobby_2', 'PRP_node_corr_back_2'),
('PRP_node_lift_2', 'PRP_node_lobby_2'),
('PRP_node_lift_2', 'PRP_node_lift_1'),
('PRP_node_lift_2', 'PRP_node_lift_3'),
('PRP_node_corr_right_2', 'PRP_node_lobby_2'),
('PRP_node_corr_right_2', 'PRP_201'),
('PRP_node_corr_right_2', 'PRP_202'),
('PRP_node_corr_right_2', 'PRP_203'),
('PRP_node_corr_right_2', 'PRP_204'),
('PRP_node_corr_right_2', 'PRP_205'),
('PRP_node_corr_left_2', 'PRP_node_lobby_2'),
('PRP_node_corr_left_2', 'PRP_206'),
('PRP_node_corr_left_2', 'PRP_207'),
('PRP_node_corr_left_2', 'PRP_208'),
('PRP_node_corr_left_2', 'PRP_209'),
('PRP_node_corr_back_2', 'PRP_node_lobby_2'),
('PRP_node_corr_back_2', 'PRP_210'),
('PRP_node_corr_back_2', 'PRP_211'),
('PRP_node_corr_back_2', 'PRP_212'),
('PRP_node_corr_back_2', 'PRP_213'),
('PRP_201', 'PRP_node_corr_right_2'),
('PRP_202', 'PRP_node_corr_right_2'),
('PRP_203', 'PRP_node_corr_right_2'),
('PRP_204', 'PRP_node_corr_right_2'),
('PRP_205', 'PRP_node_corr_right_2'),
('PRP_206', 'PRP_node_corr_left_2'),
('PRP_207', 'PRP_node_corr_left_2'),
('PRP_208', 'PRP_node_corr_left_2'),
('PRP_209', 'PRP_node_corr_left_2'),
('PRP_210', 'PRP_node_corr_back_2'),
('PRP_211', 'PRP_node_corr_back_2'),
('PRP_212', 'PRP_node_corr_back_2'),
('PRP_213', 'PRP_node_corr_back_2'),
('PRP_node_lobby_3', 'PRP_node_lift_3'),
('PRP_node_lobby_3', 'PRP_node_corr_right_3'),
('PRP_node_lobby_3', 'PRP_node_corr_left_3'),
('PRP_node_lobby_3', 'PRP_node_corr_back_3'),
('PRP_node_lift_3', 'PRP_node_lobby_3'),
('PRP_node_lift_3', 'PRP_node_lift_2'),
('PRP_node_lift_3', 'PRP_node_lift_4'),
('PRP_node_corr_right_3', 'PRP_node_lobby_3'),
('PRP_node_corr_right_3', 'PRP_301'),
('PRP_node_corr_right_3', 'PRP_302'),
('PRP_node_corr_right_3', 'PRP_303'),
('PRP_node_corr_right_3', 'PRP_304'),
('PRP_node_corr_left_3', 'PRP_node_lobby_3'),
('PRP_node_corr_left_3', 'PRP_305'),
('PRP_node_corr_left_3', 'PRP_306'),
('PRP_node_corr_left_3', 'PRP_307'),
('PRP_node_corr_left_3', 'PRP_308'),
('PRP_node_corr_back_3', 'PRP_node_lobby_3'),
('PRP_node_corr_back_3', 'PRP_310'),
('PRP_node_corr_back_3', 'PRP_311'),
('PRP_node_corr_back_3', 'PRP_312'),
('PRP_node_corr_back_3', 'PRP_313'),
('PRP_301', 'PRP_node_corr_right_3'),
('PRP_302', 'PRP_node_corr_right_3'),
('PRP_303', 'PRP_node_corr_right_3'),
('PRP_304', 'PRP_node_corr_right_3'),
('PRP_305', 'PRP_node_corr_left_3'),
('PRP_306', 'PRP_node_corr_left_3'),
('PRP_307', 'PRP_node_corr_left_3'),
('PRP_308', 'PRP_node_corr_left_3'),
('PRP_310', 'PRP_node_corr_back_3'),
('PRP_311', 'PRP_node_corr_back_3'),
('PRP_312', 'PRP_node_corr_back_3'),
('PRP_313', 'PRP_node_corr_back_3'),
('PRP_node_lobby_4', 'PRP_node_lift_4'),
('PRP_node_lobby_4', 'PRP_node_corr_right_4'),
('PRP_node_lobby_4', 'PRP_node_corr_left_4'),
('PRP_node_lobby_4', 'PRP_node_corr_back_4'),
('PRP_node_lift_4', 'PRP_node_lobby_4'),
('PRP_node_lift_4', 'PRP_node_lift_3'),
('PRP_node_lift_4', 'PRP_node_lift_5'),
('PRP_node_corr_right_4', 'PRP_node_lobby_4'),
('PRP_node_corr_right_4', 'PRP_401'),
('PRP_node_corr_right_4', 'PRP_402'),
('PRP_node_corr_right_4', 'PRP_403'),
('PRP_node_corr_right_4', 'PRP_404'),
('PRP_node_corr_left_4', 'PRP_node_lobby_4'),
('PRP_node_corr_left_4', 'PRP_405'),
('PRP_node_corr_left_4', 'PRP_406'),
('PRP_node_corr_left_4', 'PRP_407'),
('PRP_node_corr_left_4', 'PRP_408'),
('PRP_node_corr_back_4', 'PRP_node_lobby_4'),
('PRP_node_corr_back_4', 'PRP_410'),
('PRP_node_corr_back_4', 'PRP_411'),
('PRP_node_corr_back_4', 'PRP_412'),
('PRP_node_corr_back_4', 'PRP_413'),
('PRP_401', 'PRP_node_corr_right_4'),
('PRP_402', 'PRP_node_corr_right_4'),
('PRP_403', 'PRP_node_corr_right_4'),
('PRP_404', 'PRP_node_corr_right_4'),
('PRP_405', 'PRP_node_corr_left_4'),
('PRP_406', 'PRP_node_corr_left_4'),
('PRP_407', 'PRP_node_corr_left_4'),
('PRP_408', 'PRP_node_corr_left_4'),
('PRP_410', 'PRP_node_corr_back_4'),
('PRP_411', 'PRP_node_corr_back_4'),
('PRP_412', 'PRP_node_corr_back_4'),
('PRP_413', 'PRP_node_corr_back_4'),
('PRP_node_lobby_5', 'PRP_node_lift_5'),
('PRP_node_lobby_5', 'PRP_node_corr_right_5'),
('PRP_node_lobby_5', 'PRP_node_corr_left_5'),
('PRP_node_lobby_5', 'PRP_node_corr_back_5'),
('PRP_node_lift_5', 'PRP_node_lobby_5'),
('PRP_node_lift_5', 'PRP_node_lift_4'),
('PRP_node_lift_5', 'PRP_node_lift_6'),
('PRP_node_corr_right_5', 'PRP_node_lobby_5'),
('PRP_node_corr_right_5', 'PRP_501'),
('PRP_node_corr_right_5', 'PRP_502'),
('PRP_node_corr_right_5', 'PRP_503'),
('PRP_node_corr_right_5', 'PRP_504'),
('PRP_node_corr_left_5', 'PRP_node_lobby_5'),
('PRP_node_corr_left_5', 'PRP_505'),
('PRP_node_corr_left_5', 'PRP_506'),
('PRP_node_corr_left_5', 'PRP_507'),
('PRP_node_corr_left_5', 'PRP_508'),
('PRP_node_corr_back_5', 'PRP_node_lobby_5'),
('PRP_node_corr_back_5', 'PRP_510'),
('PRP_node_corr_back_5', 'PRP_511'),
('PRP_node_corr_back_5', 'PRP_512'),
('PRP_node_corr_back_5', 'PRP_513'),
('PRP_501', 'PRP_node_corr_right_5'),
('PRP_502', 'PRP_node_corr_right_5'),
('PRP_503', 'PRP_node_corr_right_5'),
('PRP_504', 'PRP_node_corr_right_5'),
('PRP_505', 'PRP_node_corr_left_5'),
('PRP_506', 'PRP_node_corr_left_5'),
('PRP_507', 'PRP_node_corr_left_5'),
('PRP_508', 'PRP_node_corr_left_5'),
('PRP_510', 'PRP_node_corr_back_5'),
('PRP_511', 'PRP_node_corr_back_5'),
('PRP_512', 'PRP_node_corr_back_5'),
('PRP_513', 'PRP_node_corr_back_5'),
('PRP_node_lobby_6', 'PRP_node_lift_6'),
('PRP_node_lobby_6', 'PRP_node_corr_right_6'),
('PRP_node_lobby_6', 'PRP_node_corr_left_6'),
('PRP_node_lobby_6', 'PRP_node_corr_back_6'),
('PRP_node_lift_6', 'PRP_node_lobby_6'),
('PRP_node_lift_6', 'PRP_node_lift_5'),
('PRP_node_lift_6', 'PRP_node_lift_7'),
('PRP_node_corr_right_6', 'PRP_node_lobby_6'),
('PRP_node_corr_right_6', 'PRP_601'),
('PRP_node_corr_right_6', 'PRP_602'),
('PRP_node_corr_right_6', 'PRP_603'),
('PRP_node_corr_left_6', 'PRP_node_lobby_6'),
('PRP_node_corr_left_6', 'PRP_605'),
('PRP_node_corr_left_6', 'PRP_606'),
('PRP_node_corr_left_6', 'PRP_607'),
('PRP_node_corr_back_6', 'PRP_node_lobby_6'),
('PRP_node_corr_back_6', 'PRP_610'),
('PRP_node_corr_back_6', 'PRP_611'),
('PRP_node_corr_back_6', 'PRP_612'),
('PRP_node_corr_back_6', 'PRP_613'),
('PRP_601', 'PRP_node_corr_right_6'),
('PRP_602', 'PRP_node_corr_right_6'),
('PRP_603', 'PRP_node_corr_right_6'),
('PRP_605', 'PRP_node_corr_left_6'),
('PRP_606', 'PRP_node_corr_left_6'),
('PRP_607', 'PRP_node_corr_left_6'),
('PRP_610', 'PRP_node_corr_back_6'),
('PRP_611', 'PRP_node_corr_back_6'),
('PRP_612', 'PRP_node_corr_back_6'),
('PRP_613', 'PRP_node_corr_back_6'),
('PRP_node_lobby_7', 'PRP_node_lift_7'),
('PRP_node_lobby_7', 'PRP_node_corr_right_7'),
('PRP_node_lobby_7', 'PRP_node_corr_left_7'),
('PRP_node_lobby_7', 'PRP_node_corr_back_7'),
('PRP_node_lift_7', 'PRP_node_lobby_7'),
('PRP_node_lift_7', 'PRP_node_lift_6'),
('PRP_node_corr_right_7', 'PRP_node_lobby_7'),
('PRP_node_corr_right_7', 'PRP_701'),
('PRP_node_corr_right_7', 'PRP_702'),
('PRP_node_corr_right_7', 'PRP_703'),
('PRP_node_corr_left_7', 'PRP_node_lobby_7'),
('PRP_node_corr_left_7', 'PRP_705'),
('PRP_node_corr_left_7', 'PRP_706'),
('PRP_node_corr_left_7', 'PRP_707'),
('PRP_node_corr_back_7', 'PRP_node_lobby_7'),
('PRP_node_corr_back_7', 'PRP_710'),
('PRP_node_corr_back_7', 'PRP_711'),
('PRP_node_corr_back_7', 'PRP_712'),
('PRP_701', 'PRP_node_corr_right_7'),
('PRP_702', 'PRP_node_corr_right_7'),
('PRP_703', 'PRP_node_corr_right_7'),
('PRP_705', 'PRP_node_corr_left_7'),
('PRP_706', 'PRP_node_corr_left_7'),
('PRP_707', 'PRP_node_corr_left_7'),
('PRP_710', 'PRP_node_corr_back_7'),
('PRP_711', 'PRP_node_corr_back_7'),
('PRP_712', 'PRP_node_corr_back_7'),
('sjt_entrance_G', 'sjt_atrium_G'),
('sjt_atrium_G', 'sjt_entrance_G'),
('sjt_atrium_G', 'sjt_lift_G'),
('sjt_atrium_G', 'sjt_corr_N_G'),
('sjt_atrium_G', 'sjt_corr_S_G'),
('sjt_atrium_G', 'sjt_corr_E_G'),
('sjt_atrium_G', 'sjt_corr_W_G'),
('sjt_lift_G', 'sjt_atrium_G'),
('sjt_lift_G', 'sjt_lift_1'),
('sjt_corr_N_G', 'sjt_atrium_G'),
('sjt_corr_N_G', 'SJT_G13'),
('sjt_corr_N_G', 'SJT_G11'),
('sjt_corr_N_G', 'SJT_G12'),
('sjt_corr_S_G', 'sjt_atrium_G'),
('sjt_corr_S_G', 'SJT_PAT_Office'),
('sjt_corr_S_G', 'SJT_G01'),
('sjt_corr_S_G', 'SJT_G14'),
('sjt_corr_E_G', 'sjt_atrium_G'),
('sjt_corr_E_G', 'SJT_G17'),
('sjt_corr_E_G', 'SJT_G18'),
('sjt_corr_E_G', 'SJT_G16'),
('sjt_corr_W_G', 'sjt_atrium_G'),
('sjt_corr_W_G', 'sjt_restroom_M_G'),
('sjt_corr_W_G', 'sjt_restroom_F_G'),
('SJT_G13', 'sjt_corr_N_G'),
('SJT_G11', 'sjt_corr_N_G'),
('SJT_G12', 'sjt_corr_N_G'),
('SJT_PAT_Office', 'sjt_corr_S_G'),
('SJT_G01', 'sjt_corr_S_G'),
('SJT_G14', 'sjt_corr_S_G'),
('SJT_G17', 'sjt_corr_E_G'),
('SJT_G18', 'sjt_corr_E_G'),
('SJT_G16', 'sjt_corr_E_G'),
('sjt_restroom_M_G', 'sjt_corr_W_G'),
('sjt_restroom_F_G', 'sjt_corr_W_G'),
('sjt_atrium_1', 'sjt_lift_1'),
('sjt_atrium_1', 'sjt_corr_N_1'),
('sjt_atrium_1', 'sjt_corr_S_1'),
('sjt_atrium_1', 'sjt_corr_E_1'),
('sjt_atrium_1', 'sjt_corr_W_1'),
('sjt_lift_1', 'sjt_atrium_1'),
('sjt_lift_1', 'sjt_lift_G'),
('sjt_lift_1', 'sjt_lift_2'),
('sjt_corr_N_1', 'sjt_atrium_1'),
('sjt_corr_N_1', 'SJT_121A'),
('sjt_corr_N_1', 'SJT_122'),
('sjt_corr_S_1', 'sjt_atrium_1'),
('sjt_corr_S_1', 'SJT_124'),
('sjt_corr_S_1', 'SJT_125'),
('sjt_corr_S_1', 'SJT_126'),
('sjt_corr_S_1', 'SJT_127'),
('sjt_corr_E_1', 'sjt_atrium_1'),
('sjt_corr_E_1', 'SJT_130'),
('sjt_corr_E_1', 'SJT_131'),
('sjt_corr_W_1', 'sjt_atrium_1'),
('sjt_corr_W_1', 'sjt_restroom_M_1'),
('sjt_corr_W_1', 'sjt_restroom_F_1'),
('sjt_corr_W_1', 'SJT_123'),
('SJT_121A', 'sjt_corr_N_1'),
('SJT_122', 'sjt_corr_N_1'),
('SJT_124', 'sjt_corr_S_1'),
('SJT_125', 'sjt_corr_S_1'),
('SJT_126', 'sjt_corr_S_1'),
('SJT_127', 'sjt_corr_S_1'),
('SJT_130', 'sjt_corr_E_1'),
('SJT_131', 'sjt_corr_E_1'),
('sjt_restroom_M_1', 'sjt_corr_W_1'),
('sjt_restroom_F_1', 'sjt_corr_W_1'),
('SJT_123', 'sjt_corr_W_1'),
('sjt_atrium_2', 'sjt_lift_2'),
('sjt_atrium_2', 'sjt_corr_N_2'),
('sjt_atrium_2', 'sjt_corr_S_2'),
('sjt_atrium_2', 'sjt_corr_E_2'),
('sjt_atrium_2', 'sjt_corr_W_2'),
('sjt_lift_2', 'sjt_atrium_2'),
('sjt_lift_2', 'sjt_lift_1'),
('sjt_lift_2', 'sjt_lift_3'),
('sjt_corr_N_2', 'sjt_atrium_2'),
('sjt_corr_N_2', 'SJT_216'),
('sjt_corr_N_2', 'SJT_217'),
('sjt_corr_N_2', 'SJT_218'),
('sjt_corr_N_2', 'SJT_219'),
('sjt_corr_S_2', 'sjt_atrium_2'),
('sjt_corr_S_2', 'SJT_207A'),
('sjt_corr_S_2', 'SJT_208'),
('sjt_corr_S_2', 'SJT_211'),
('sjt_corr_S_2', 'SJT_215'),
('sjt_corr_E_2', 'sjt_atrium_2'),
('sjt_corr_E_2', 'SJT_210'),
('sjt_corr_E_2', 'SJT_213'),
('sjt_corr_E_2', 'SJT_217A'),
('sjt_corr_W_2', 'sjt_atrium_2'),
('sjt_corr_W_2', 'SJT_209'),
('sjt_corr_W_2', 'SJT_214'),
('sjt_corr_W_2', 'SJT_220'),
('SJT_216', 'sjt_corr_N_2'),
('SJT_217', 'sjt_corr_N_2'),
('SJT_218', 'sjt_corr_N_2'),
('SJT_219', 'sjt_corr_N_2'),
('SJT_207A', 'sjt_corr_S_2'),
('SJT_208', 'sjt_corr_S_2'),
('SJT_211', 'sjt_corr_S_2'),
('SJT_215', 'sjt_corr_S_2'),
('SJT_210', 'sjt_corr_E_2'),
('SJT_213', 'sjt_corr_E_2'),
('SJT_217A', 'sjt_corr_E_2'),
('SJT_209', 'sjt_corr_W_2'),
('SJT_214', 'sjt_corr_W_2'),
('SJT_220', 'sjt_corr_W_2'),
('sjt_atrium_3', 'sjt_lift_3'),
('sjt_atrium_3', 'sjt_corr_N_3'),
('sjt_atrium_3', 'sjt_corr_S_3'),
('sjt_atrium_3', 'sjt_corr_E_3'),
('sjt_atrium_3', 'sjt_corr_W_3'),
('sjt_lift_3', 'sjt_atrium_3'),
('sjt_lift_3', 'sjt_lift_2'),
('sjt_lift_3', 'sjt_lift_4'),
('sjt_corr_N_3', 'sjt_atrium_3'),
('sjt_corr_N_3', 'SJT_301'),
('sjt_corr_N_3', 'SJT_302'),
('sjt_corr_N_3', 'SJT_303'),
('sjt_corr_N_3', 'SJT_304'),
('sjt_corr_S_3', 'sjt_atrium_3'),
('sjt_corr_S_3', 'SJT_305'),
('sjt_corr_S_3', 'SJT_306'),
('sjt_corr_S_3', 'SJT_307'),
('sjt_corr_S_3', 'SJT_308'),
('sjt_corr_E_3', 'sjt_atrium_3'),
('sjt_corr_E_3', 'SJT_309'),
('sjt_corr_E_3', 'SJT_310'),
('sjt_corr_E_3', 'SJT_311'),
('sjt_corr_W_3', 'sjt_atrium_3'),
('sjt_corr_W_3', 'sjt_restroom_M_3'),
('sjt_corr_W_3', 'sjt_restroom_F_3'),
('SJT_301', 'sjt_corr_N_3'),
('SJT_302', 'sjt_corr_N_3'),
('SJT_303', 'sjt_corr_N_3'),
('SJT_304', 'sjt_corr_N_3'),
('SJT_305', 'sjt_corr_S_3'),
('SJT_306', 'sjt_corr_S_3'),
('SJT_307', 'sjt_corr_S_3'),
('SJT_308', 'sjt_corr_S_3'),
('SJT_309', 'sjt_corr_E_3'),
('SJT_310', 'sjt_corr_E_3'),
('SJT_311', 'sjt_corr_E_3'),
('sjt_restroom_M_3', 'sjt_corr_W_3'),
('sjt_restroom_F_3', 'sjt_corr_W_3'),
('sjt_atrium_4', 'sjt_lift_4'),
('sjt_atrium_4', 'sjt_corr_N_4'),
('sjt_atrium_4', 'sjt_corr_S_4'),
('sjt_atrium_4', 'sjt_corr_E_4'),
('sjt_atrium_4', 'sjt_corr_W_4'),
('sjt_lift_4', 'sjt_atrium_4'),
('sjt_lift_4', 'sjt_lift_3'),
('sjt_lift_4', 'sjt_lift_5'),
('sjt_corr_N_4', 'sjt_atrium_4'),
('sjt_corr_N_4', 'SJT_401'),
('sjt_corr_N_4', 'SJT_402'),
('sjt_corr_N_4', 'SJT_403'),
('sjt_corr_N_4', 'SJT_404'),
('sjt_corr_S_4', 'sjt_atrium_4'),
('sjt_corr_S_4', 'SJT_405'),
('sjt_corr_S_4', 'SJT_406'),
('sjt_corr_S_4', 'SJT_407'),
('sjt_corr_S_4', 'SJT_408'),
('sjt_corr_E_4', 'sjt_atrium_4'),
('sjt_corr_E_4', 'SJT_409'),
('sjt_corr_E_4', 'SJT_410'),
('sjt_corr_E_4', 'SJT_411'),
('sjt_corr_W_4', 'sjt_atrium_4'),
('sjt_corr_W_4', 'sjt_restroom_M_4'),
('sjt_corr_W_4', 'sjt_restroom_F_4'),
('SJT_401', 'sjt_corr_N_4'),
('SJT_402', 'sjt_corr_N_4'),
('SJT_403', 'sjt_corr_N_4'),
('SJT_404', 'sjt_corr_N_4'),
('SJT_405', 'sjt_corr_S_4'),
('SJT_406', 'sjt_corr_S_4'),
('SJT_407', 'sjt_corr_S_4'),
('SJT_408', 'sjt_corr_S_4'),
('SJT_409', 'sjt_corr_E_4'),
('SJT_410', 'sjt_corr_E_4'),
('SJT_411', 'sjt_corr_E_4'),
('sjt_restroom_M_4', 'sjt_corr_W_4'),
('sjt_restroom_F_4', 'sjt_corr_W_4'),
('sjt_atrium_5', 'sjt_lift_5'),
('sjt_atrium_5', 'sjt_corr_N_5'),
('sjt_atrium_5', 'sjt_corr_S_5'),
('sjt_atrium_5', 'sjt_corr_E_5'),
('sjt_atrium_5', 'sjt_corr_W_5'),
('sjt_lift_5', 'sjt_atrium_5'),
('sjt_lift_5', 'sjt_lift_4'),
('sjt_lift_5', 'sjt_lift_6'),
('sjt_corr_N_5', 'sjt_atrium_5'),
('sjt_corr_N_5', 'SJT_501'),
('sjt_corr_N_5', 'SJT_502'),
('sjt_corr_N_5', 'SJT_503'),
('sjt_corr_N_5', 'SJT_504'),
('sjt_corr_S_5', 'sjt_atrium_5'),
('sjt_corr_S_5', 'SJT_505'),
('sjt_corr_S_5', 'SJT_506'),
('sjt_corr_S_5', 'SJT_507'),
('sjt_corr_S_5', 'SJT_508'),
('sjt_corr_E_5', 'sjt_atrium_5'),
('sjt_corr_E_5', 'SJT_509'),
('sjt_corr_E_5', 'SJT_510'),
('sjt_corr_E_5', 'SJT_511'),
('sjt_corr_W_5', 'sjt_atrium_5'),
('sjt_corr_W_5', 'sjt_restroom_M_5'),
('sjt_corr_W_5', 'sjt_restroom_F_5'),
('SJT_501', 'sjt_corr_N_5'),
('SJT_502', 'sjt_corr_N_5'),
('SJT_503', 'sjt_corr_N_5'),
('SJT_504', 'sjt_corr_N_5'),
('SJT_505', 'sjt_corr_S_5'),
('SJT_506', 'sjt_corr_S_5'),
('SJT_507', 'sjt_corr_S_5'),
('SJT_508', 'sjt_corr_S_5'),
('SJT_509', 'sjt_corr_E_5'),
('SJT_510', 'sjt_corr_E_5'),
('SJT_511', 'sjt_corr_E_5'),
('sjt_restroom_M_5', 'sjt_corr_W_5'),
('sjt_restroom_F_5', 'sjt_corr_W_5'),
('sjt_atrium_6', 'sjt_lift_6'),
('sjt_atrium_6', 'sjt_corr_N_6'),
('sjt_atrium_6', 'sjt_corr_S_6'),
('sjt_atrium_6', 'sjt_corr_E_6'),
('sjt_atrium_6', 'sjt_corr_W_6'),
('sjt_lift_6', 'sjt_atrium_6'),
('sjt_lift_6', 'sjt_lift_5'),
('sjt_lift_6', 'sjt_lift_7'),
('sjt_corr_N_6', 'sjt_atrium_6'),
('sjt_corr_N_6', 'SJT_601'),
('sjt_corr_N_6', 'SJT_602'),
('sjt_corr_N_6', 'SJT_603'),
('sjt_corr_N_6', 'SJT_604'),
('sjt_corr_S_6', 'sjt_atrium_6'),
('sjt_corr_S_6', 'SJT_605'),
('sjt_corr_S_6', 'SJT_606'),
('sjt_corr_S_6', 'SJT_607'),
('sjt_corr_S_6', 'SJT_608'),
('sjt_corr_E_6', 'sjt_atrium_6'),
('sjt_corr_E_6', 'SJT_609'),
('sjt_corr_E_6', 'SJT_610'),
('sjt_corr_E_6', 'SJT_611'),
('sjt_corr_W_6', 'sjt_atrium_6'),
('sjt_corr_W_6', 'sjt_restroom_M_6'),
('sjt_corr_W_6', 'sjt_restroom_F_6'),
('SJT_601', 'sjt_corr_N_6'),
('SJT_602', 'sjt_corr_N_6'),
('SJT_603', 'sjt_corr_N_6'),
('SJT_604', 'sjt_corr_N_6'),
('SJT_605', 'sjt_corr_S_6'),
('SJT_606', 'sjt_corr_S_6'),
('SJT_607', 'sjt_corr_S_6'),
('SJT_608', 'sjt_corr_S_6'),
('SJT_609', 'sjt_corr_E_6'),
('SJT_610', 'sjt_corr_E_6'),
('SJT_611', 'sjt_corr_E_6'),
('sjt_restroom_M_6', 'sjt_corr_W_6'),
('sjt_restroom_F_6', 'sjt_corr_W_6'),
('sjt_atrium_7', 'sjt_lift_7'),
('sjt_atrium_7', 'sjt_corr_N_7'),
('sjt_atrium_7', 'sjt_corr_S_7'),
('sjt_atrium_7', 'sjt_corr_E_7'),
('sjt_atrium_7', 'sjt_corr_W_7'),
('sjt_lift_7', 'sjt_atrium_7'),
('sjt_lift_7', 'sjt_lift_6'),
('sjt_lift_7', 'sjt_lift_8'),
('sjt_corr_N_7', 'sjt_atrium_7'),
('sjt_corr_N_7', 'SJT_701'),
('sjt_corr_N_7', 'SJT_702'),
('sjt_corr_N_7', 'SJT_703'),
('sjt_corr_N_7', 'SJT_704'),
('sjt_corr_S_7', 'sjt_atrium_7'),
('sjt_corr_S_7', 'SJT_705'),
('sjt_corr_S_7', 'SJT_706'),
('sjt_corr_S_7', 'SJT_707'),
('sjt_corr_S_7', 'SJT_708'),
('sjt_corr_E_7', 'sjt_atrium_7'),
('sjt_corr_E_7', 'SJT_709'),
('sjt_corr_E_7', 'SJT_710'),
('sjt_corr_E_7', 'SJT_711'),
('sjt_corr_W_7', 'sjt_atrium_7'),
('sjt_corr_W_7', 'sjt_restroom_M_7'),
('sjt_corr_W_7', 'sjt_restroom_F_7'),
('SJT_701', 'sjt_corr_N_7'),
('SJT_702', 'sjt_corr_N_7'),
('SJT_703', 'sjt_corr_N_7'),
('SJT_704', 'sjt_corr_N_7'),
('SJT_705', 'sjt_corr_S_7'),
('SJT_706', 'sjt_corr_S_7'),
('SJT_707', 'sjt_corr_S_7'),
('SJT_708', 'sjt_corr_S_7'),
('SJT_709', 'sjt_corr_E_7'),
('SJT_710', 'sjt_corr_E_7'),
('SJT_711', 'sjt_corr_E_7'),
('sjt_restroom_M_7', 'sjt_corr_W_7'),
('sjt_restroom_F_7', 'sjt_corr_W_7'),
('sjt_atrium_8', 'sjt_lift_8'),
('sjt_atrium_8', 'sjt_corr_N_8'),
('sjt_atrium_8', 'sjt_corr_S_8'),
('sjt_atrium_8', 'sjt_corr_E_8'),
('sjt_atrium_8', 'sjt_corr_W_8'),
('sjt_lift_8', 'sjt_atrium_8'),
('sjt_lift_8', 'sjt_lift_7'),
('sjt_corr_N_8', 'sjt_atrium_8'),
('sjt_corr_N_8', 'SJT_801'),
('sjt_corr_N_8', 'SJT_802'),
('sjt_corr_N_8', 'SJT_803'),
('sjt_corr_N_8', 'SJT_804'),
('sjt_corr_S_8', 'sjt_atrium_8'),
('sjt_corr_S_8', 'SJT_805'),
('sjt_corr_S_8', 'SJT_806'),
('sjt_corr_S_8', 'SJT_807'),
('sjt_corr_S_8', 'SJT_808'),
('sjt_corr_E_8', 'sjt_atrium_8'),
('sjt_corr_E_8', 'SJT_809'),
('sjt_corr_E_8', 'SJT_810'),
('sjt_corr_E_8', 'SJT_811'),
('sjt_corr_W_8', 'sjt_atrium_8'),
('sjt_corr_W_8', 'sjt_restroom_M_8'),
('sjt_corr_W_8', 'sjt_restroom_F_8'),
('SJT_801', 'sjt_corr_N_8'),
('SJT_802', 'sjt_corr_N_8'),
('SJT_803', 'sjt_corr_N_8'),
('SJT_804', 'sjt_corr_N_8'),
('SJT_805', 'sjt_corr_S_8'),
('SJT_806', 'sjt_corr_S_8'),
('SJT_807', 'sjt_corr_S_8'),
('SJT_808', 'sjt_corr_S_8'),
('SJT_809', 'sjt_corr_E_8'),
('SJT_810', 'sjt_corr_E_8'),
('SJT_811', 'sjt_corr_E_8'),
('sjt_restroom_M_8', 'sjt_corr_W_8'),
('sjt_restroom_F_8', 'sjt_corr_W_8'),
('SJT_4_LOBBY', 'SJT_411'),
('SJT_5_LOBBY', 'SJT_511'),
('SJT_6_LOBBY', 'SJT_611'),
('SJT_8_LOBBY', 'SJT_811'),
('SJT_G_LOBBY', 'SJT_G_FOOD'),
('SJT_3_LOBBY', 'SJT_3_PAT'),
('SJT_3_PAT', 'SJT_3_GD'),
('SJT_G_LOBBY', 'SJT_3_LOBBY'),
('SJT_3_LOBBY', 'SJT_4_LOBBY'),
('SJT_4_LOBBY', 'SJT_5_LOBBY'),
('SJT_5_LOBBY', 'SJT_6_LOBBY'),
('SJT_6_LOBBY', 'SJT_8_LOBBY'),
('TT_ENT', 'TT_G_LOBBY'),
('TT_G_LOBBY', 'TT_G01'),
('TT_G_LOBBY', 'TT_G02'),
('TT_G_LOBBY', 'TT_G03'),
('TT_1_LOBBY', 'TT_101'),
('TT_1_LOBBY', 'TT_102'),
('TT_1_LOBBY', 'TT_103'),
('TT_1_LOBBY', 'TT_104'),
('TT_2_LOBBY', 'TT_201'),
('TT_2_LOBBY', 'TT_202'),
('TT_2_LOBBY', 'TT_203'),
('TT_2_LOBBY', 'TT_204'),
('TT_3_LOBBY', 'TT_301'),
('TT_3_LOBBY', 'TT_302'),
('TT_3_LOBBY', 'TT_303'),
('TT_3_LOBBY', 'TT_304'),
('TT_4_LOBBY', 'TT_401'),
('TT_4_LOBBY', 'TT_402'),
('TT_4_LOBBY', 'TT_403'),
('TT_4_LOBBY', 'TT_404'),
('TT_5_LOBBY', 'TT_501'),
('TT_5_LOBBY', 'TT_502'),
('TT_5_LOBBY', 'TT_503'),
('TT_5_LOBBY', 'TT_504'),
('TT_6_LOBBY', 'TT_601'),
('TT_6_LOBBY', 'TT_602'),
('TT_6_LOBBY', 'TT_603'),
('TT_6_LOBBY', 'TT_604'),
('TT_7_LOBBY', 'TT_701'),
('TT_7_LOBBY', 'TT_702'),
('TT_7_LOBBY', 'TT_703'),
('TT_7_LOBBY', 'TT_704'),
('TT_G_LOBBY', 'TT_1_LOBBY'),
('TT_1_LOBBY', 'TT_2_LOBBY'),
('TT_2_LOBBY', 'TT_3_LOBBY'),
('TT_3_LOBBY', 'TT_4_LOBBY'),
('TT_4_LOBBY', 'TT_5_LOBBY'),
('TT_5_LOBBY', 'TT_6_LOBBY'),
('TT_6_LOBBY', 'TT_7_LOBBY'),
('TT_G_LOBBY', 'TT_G_FOOD'),
('TT_1_LOBBY', 'TT_1_LIBRARY')
ON CONFLICT DO NOTHING;
